environments: 
  dev1:
    values:
    - dev1/appVersions.yaml
  test1:
    values:
    - test1/appVersions.yaml
       
releases:
  - name: address-business-service-{{ .Environment.Name }}
    chart: ./mychart
    missingFileHandler: Warn
    values:
      - ./global/address-business-service.yaml
      - ./{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml
      - AppVersion: {{ .Values.address_business_service }}
   
  - name: service-registry-business-service-{{ .Environment.Name }}
    chart: ./mychart
    missingFileHandler: Warn
    values:
      - ./global/service-registry-business-service.yaml
      - ./{{ .Environment.Name }}/{{`{{ .Release.Name }}`}}.yaml
      - AppVersion: {{ .Values.address_business_service }}
      
