environments: 
  dev1:
    values:
    - dev1/services-bmco-dev1.yaml
    - dev1/services-bmom-dev1.yaml
  test1:
    values:
    - test1/services-test1.yaml

releases:
 {{- range .Values.bmco.services }}
  - name: {{ .name }}-{{`{{ .Environment.Name  }}`}}
    chart: ./bmp-chart
    missingFileHandler: Warn
    values:
      - ./global/bmco/{{ .name }}.yaml
      - ./{{`{{ .Environment.Name  }}`}}/{{`{{ .Environment.Name  }}`}}.yaml
      - ./{{`{{ .Environment.Name  }}`}}/bmco-{{`{{ .Environment.Name  }}`}}.yaml
      - ./{{`{{ .Environment.Name  }}`}}/bmco/{{`{{ .Release.Name }}`}}.yaml
      - AppVersion: {{ .version }}   
{{ end }}

 {{- range .Values.bmom.services }}
  - name: {{ .name }}-{{`{{ .Environment.Name  }}`}}
    chart: ./bmp-chart
    missingFileHandler: Warn
    values:
      - ./global/bmom/{{ .name }}.yaml
      - ./{{`{{ .Environment.Name  }}`}}/{{`{{ .Environment.Name  }}`}}.yaml
      - ./{{`{{ .Environment.Name  }}`}}/bmom-{{`{{ .Environment.Name  }}`}}.yaml
      - ./{{`{{ .Environment.Name  }}`}}/bmom/{{`{{ .Release.Name }}`}}.yaml
      - AppVersion: {{ .version }}   
{{ end }}

 