environments: 
  dev1:
    values:
    - dev1/services.yaml
  test1:
    values:
    - test1/services.yaml

releases:
 {{- range .Values.services }}
  - name: {{ .name }}-{{`{{ .Environment.Name  }}`}}
    chart: ./mychart
    missingFileHandler: Warn
    values:
      - ./global/{{ .name }}.yaml
      - ./{{`{{ .Environment.Name  }}`}}.yaml
      - ./{{`{{ .Environment.Name  }}`}}/{{`{{ .Release.Name }}`}}.yaml
      - AppVersion: {{ .version }}   
{{ end }}