apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.APP_API_NAME }}
data:
    application.properties: |-  
{{- range $key, $value := .Values.configmap_properties  }}
  {{ $key | indent 8 -}} = {{ $value -}}
{{ end }}

{{ toYaml .Values.configmap_properties | indent 4 }}
      
