apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.APP_API_NAME }}
data:
    application.yaml: |-  
{{ toYaml .Values.configmap_properties | indent 8 }}

{{ toYaml .Values.configmap_properties | indent 4 }}
      
