apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.APP_API_NAME  }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.APP_API_NAME }}
